# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = JA_AdamBurzynski_Steganography
DESTDIR = ./x64/Release
CONFIG += release
LIBS += -L"." \
    -lJA_asmAlgo \
    -lJA_cppAlgo
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(JA_AdamBurzynski_Steganography.pri)
